### ISSUE TITLE
모델이 궁금합니다.

### ISSUE THREAD

**Issue by gyunggyung** [jeina7/AI_Bookathon#1]
안녕하세요.

ko-gpt를 쓰신건지? 아니면 open ai에서 공개한 일반 모델을 fine-tuning 하신 건지 궁금합니다. 그리고 파라미터의 개수도 궁금합니다.

감사합니다 :)

**Comment by jeina7** [comment]
안녕하세요.

모델은 마인즈랩에서 제공한 한국어 기반 GPT-2 모델을 사용하였습니다. 대회에서만 공개되었고, 외부에 공개되지는 않은 것으로 알고 있습니다. 대회 소개 당시 GPT-2 Medium (355M) 구조를 기반으로 사전학습된 모델이라고 소개받은 것으로 기억합니다. 

감사합니다 :)

**Comment by gyunggyung** [comment]
답변 감사합니다!

한 가지 질문만 더 드리고 싶습니다.

수집하신 데이터를 github에 올리실 생각은 없으신가요? 혹은 개인적으로 받는 것이 가능할까요?

감사합니다.

**Comment by jeina7** [comment]
데이터를 어떤 목적으로 사용할 예정이신지 말씀해주시면 고려해보겠습니다. 
ai.developer@kakao.com 으로 메일 주세요!

**Comment by gyunggyung** [comment]
목적은 크게 2개 입니다.

1. 실제로 저렇게 결과가 잘 나오는지, 제 모델을 통해서 재현하는 것입니다.

2. 개인적인 프로젝트 서비스를 위해서 학습 데이터 중 하나로 쓰고 싶습니다.

감사합니다.

**Comment by gyunggyung** [comment]
답변 부탁드립니다~~
